export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const USER_LOGOUT = 'USER_LOGOUT';
export const ALL_DELIVERIES = 'ALL_DELIVERIES';
export const CONFIRMED_DELIVERIES = 'CONFIRMED_DELIVERIES';
export const SINGLE_DELIVERY = 'SINGLE_DELIVERY';
export const ACCEPT_DELIVERY = 'ACCEPT_DELIVERY';
export const FINISH_DELIVERY = 'FINISH_DELIVERY';
